### ISSUE TITLE
renovate: need to diable toolchain updates

### ISSUE THREAD

**Issue by Luap99** [containers/automation#193]
see https://github.com/containers/common/pull/1964
and https://github.com/renovatebot/renovate/issues/24427

I guess we need to tweak the config to not bump the toolchain version. Even worse we have go set the renovate go version to 1.21 yet it decided to bump toolchain to 1.22? https://github.com/containers/automation/commit/74f8447d45a96fd34cca8c4eb532a0f298a53d8b

**Comment by cevich** [comment]
Thanks for the links.  Looks like there's lots of activity (PRs/discussions) going on in this area.  https://github.com/renovatebot/renovate/pull/ 28476 suggests there's a new `depType` of `toolchain` that we could maybe hook into.  Still investigating...

**Comment by cevich** [comment]
...I spent some time looking through the linked issues/discussions and docs.  I don't see any way to restrict the `toolchain` updates in a similar way to the `go` updates.  [The configuration options simply don't exist at this time ](https://docs.renovatebot.com/golang/) :disappointed: 

Other than closing the PRs when they come up, I honestly don't know how or if this can be fixed.  I'll keep the issue open for now in case something strikes me as a fix or workaround.
